name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to InfinityFree FTP
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ftpupload.net
          username: ${{ secrets.USER_FTP }}
          password: ${{ secrets.PW_FTP }}
          local-dir: ./
          server-dir: /htdocs/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.github/**
